# Generated by Django 2.0 on 2017-12-24 23:22

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=secrets.token_urlsafe, max_length=40),
        ),
    ]
