# Generated by Django 2.0 on 2017-12-25 05:52

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171224_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=secrets.token_urlsafe, max_length=100),
        ),
    ]
