# Generated by Django 2.0.1 on 2018-01-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_total_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='_votes',
        ),
    ]
