# Generated by Django 2.0.1 on 2018-01-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180104_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('id',)},
        ),
    ]
